name: Deploy back-end project

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Server/**'

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_DEV }}

jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      
      - name: Docker login
        run: docker login --username=_ --password=${{ env.HEROKU_API_KEY }} registry.heroku.com

      - name: Build docker image
        run: docker build -f src/Server/Exchange.Portal.Web/Dockerfile -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
        
      - name: Push docker image
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
      
      - name: Publish
        run: heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}