name: Deploy project

on:
  push:
    branches:
      - main
    workflow_dispatch:

env:
  NETLIFY_AUTH_TOKEN: 0aA1VcxtCEI2hyqvp9ZzX06_2i-NMktFb1imweFnFes
  FRONT_END_ENV_SITE_ID: 712b3bd2-9839-4562-8f97-e13f9ba0db8a
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
              
      - name: Install .NET 7
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '7.0.x'
            
      - name: Build project
        run: dotnet build ExchangePortal.sln
          
  front_end_build:
    runs_on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: |
          cd src/Client/Exchange.Portal.UI
          npm run build
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
          
  front_end_deploy:
    needs: front_end_build
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output contents
        run: ls

      - name: Install netlify-cli
        run: npm install netlify-cli -g
        
      - name: Install netlify-cli
        run: netlify deploy --site ${{ env.NETLIFY_SITE_ID }} --auth ${{ env.NETLIFY_AUTH_TOKEN }} --prod
        